name: Build
on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install build-essential libasound2-dev libudev-dev
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rustfmt, clippy
    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check
    - name: Run cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Run cargo tests
      uses: actions-rs/cargo@v1
      with:
        command: test
